### ISSUE TITLE
[BUG] conduit build

### ISSUE THREAD

**Issue by keinou** [conduit-dart/conduit#82]
Error on conduit build.

**To Reproduce**
1. run conduit build

Fetching dependencies (--offline --no-precompile)...
Finished fetching dependencies.
Compiling...
*** Uncaught error
    Bad state: Bad state: 'dart2native' failed with the following message: Could not find a command named "compilie".

- OS: Linux/Debian

**Comment by jayjah** [comment]
@keinou This one is fixed, but currently not released on pub.dev. So if you override your conduit dependency in the `pubspec.yaml` file - it should work!

**Comment by keinou** [comment]
Can give a example? this is in main branch?

**Comment by jayjah** [comment]
@keinou 
> Can give a example? this is in main branch?

Yeah, it's the main/master Branch. 

Example: 
```
dependency_overrides:
  conduit:
    git:
      url: git@github.com:conduit-dart/conduit.git
      ref: master
      path: conduit

```

**Comment by BokMeng** [comment]
I also have the build error. 
I try to add the dependency_overrides in the pubspec.yaml, but still get the same error.

**Comment by keinou** [comment]
@BokMeng i resolved with this:

dependency_overrides:
  conduit_runtime:
    git:
      url: https://github.com/conduit-dart/conduit.git
      ref: master
      path: runtime
